# Generated by Django 5.0.14 on 2026-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_userprofile_bio_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/'),
        ),
    ]
